// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDD3iIefRi7fER8LejZ8XRkf2e_KpwHWXQ',
    appId: '1:440845684486:web:d7e323fdf1b4913c819887',
    messagingSenderId: '440845684486',
    projectId: 'counter-firebase-1a569',
    authDomain: 'counter-firebase-1a569.firebaseapp.com',
    storageBucket: 'counter-firebase-1a569.appspot.com',
    measurementId: 'G-0EB8MN64CY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAm6dyqqfeXzyn08Wx-7LQHr_D65LgsbQo',
    appId: '1:440845684486:android:0827a4e2da1fe590819887',
    messagingSenderId: '440845684486',
    projectId: 'counter-firebase-1a569',
    storageBucket: 'counter-firebase-1a569.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAey8FgHAcq9XscKy05PcCkUOAb1hvixgk',
    appId: '1:440845684486:ios:7ec4b915b60e959a819887',
    messagingSenderId: '440845684486',
    projectId: 'counter-firebase-1a569',
    storageBucket: 'counter-firebase-1a569.appspot.com',
    iosClientId: '440845684486-rpodv9uu8ii4bsg9e90ldiq4eg85li9a.apps.googleusercontent.com',
    iosBundleId: 'com.example.counterFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAey8FgHAcq9XscKy05PcCkUOAb1hvixgk',
    appId: '1:440845684486:ios:7ec4b915b60e959a819887',
    messagingSenderId: '440845684486',
    projectId: 'counter-firebase-1a569',
    storageBucket: 'counter-firebase-1a569.appspot.com',
    iosClientId: '440845684486-rpodv9uu8ii4bsg9e90ldiq4eg85li9a.apps.googleusercontent.com',
    iosBundleId: 'com.example.counterFirebase',
  );
}
